# Generated by Django 6.0.2 on 2026-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='mansoura', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Paymob', 'Paymob')], max_length=100),
        ),
    ]
